FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# datapeta

ini adalah data lokasi petaku

## datapeta API [/dataku]

### Get All Datapeta [GET]
list semua datapeta

+ Response 200 (application/json)
        
        {
            "dataku": [
                {
                    "lokasi": "Kost Boedjangan 886",
                    "bujur": 110.4327476011731,
                    "lintang": -6.9972956871655473
                }, 
                {
                    "lokasi": "Haha Guesthouse & Kost Semarang",
                    "bujur": 110.4327476011731,
                    "lintang": -6.9972956871655473
                }
            ]
        }